# Generated by Django 5.2.7 on 2026-01-10 11:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('service_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('corps', models.CharField(choices=[('Army', 'No Army'), ('Armored Corps', 'Armored Corps'), ('Artillery', 'Artillery'), ('Engineers', 'Engineers'), ('Signals', 'Signals'), ('Infantry', 'Infantry'), ('Army Service Corps', 'Army Service Corps'), ('Ordnance Corps', 'Ordnance Corps'), ('Electrical and Mechanical Engineering Corps', 'Electrical and Mechanical Engineering Corps'), ('Special Operations', 'Special Operations'), ('Aviation', 'Aviation'), ('Military Police', 'Military Police'), ('Army Dental Corps', 'Army Dental Corps'), ('Army Education Corps', 'Army Education Corps'), ('Army Corps of Clerks', 'Army Corps of Clerks'), ('Remounts, Veterinary and Farms Corps', 'Remounts, Veterinary and Farms Corps'), ('Army Nursing Corps', 'Army Nursing Corps')], default='No Army', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('national_id_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 10 or 17 digits', regex='^(\\d{10}|\\d{17})$')])),
                ('national_id_card', models.FileField(blank=True, null=True, upload_to='nid/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('service_id_card', models.FileField(blank=True, null=True, upload_to='service_id/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('live_photo', models.FileField(blank=True, null=True, upload_to='photos/', validators=[tasks.models.validate_jpg])),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_nid', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Spouse NID must be exactly 10 or 17 digits', regex='^(\\d{10}|\\d{17})$')])),
                ('spouse_birth_date', models.DateField(blank=True, null=True)),
                ('spouse_national_id_card', models.FileField(blank=True, null=True, upload_to='nid/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoanAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_loans', models.JSONField(blank=True, null=True)),
                ('salary_certificate', models.FileField(blank=True, null=True, upload_to='kyc_docs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('device_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_image', models.ImageField(upload_to='nid/')),
                ('service_id_image', models.ImageField(upload_to='service/')),
                ('live_photo', models.ImageField(upload_to='live/', validators=[tasks.models.validate_jpg])),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
