# Generated by Django 5.2.7 on 2026-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='basic_salary',
            new_name='total_interest',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='previous_loans',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='salary_account_number',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='salary_certificate',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
