# Generated by Django 5.2.7 on 2026-01-16 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_basic_salary_loanapplication_total_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='previous_loans',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_certificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
