# Generated by Django 5.2.7 on 2026-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_loanapplication_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
