# Generated by Django 5.2.7 on 2025-11-23 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_forcemember_mother_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='destination',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='duty',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='duty',
            name='rank',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='duty',
            name='serial_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='duty',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='duty',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='duty',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='forcemember',
            name='mother_unit',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
