# Generated by Django 5.2.7 on 2026-01-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cleared', 'Cleared')], default='Pending', max_length=20),
        ),
    ]
