# Generated by Django 5.2.7 on 2025-11-24 10:35

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_duty_destination_duty_phone_duty_rank_duty_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[tasks.models.validate_jpg]),
        ),
    ]
