# Generated by Django 5.2.7 on 2026-01-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_loanapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='status',
        ),
    ]
