# Generated by Django 5.2.7 on 2026-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
