# Generated by Django 5.2.7 on 2026-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_loanapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='previous_loans',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='salary_account_number',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='salary_certificate',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Locked interest rate at loan creation', max_digits=5),
        ),
    ]
