# Generated by Django 5.2.7 on 2026-01-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_interestrate_remove_loanapplication_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='previous_loans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='salary_certificates/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cleared', 'Cleared')], default='Pending', max_length=20),
        ),
    ]
