# Generated by Django 5.2.7 on 2026-01-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_loanapplication_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
