# Generated by Django 5.2.7 on 2026-01-21 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_loanapplication_last_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id_back',
            field=models.FileField(blank=True, null=True, upload_to='nid/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='spouse_nid_back',
            field=models.FileField(blank=True, null=True, upload_to='nid/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
