# Generated by Django 5.2.7 on 2026-01-25 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_user_national_id_back_user_spouse_nid_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('months', models.PositiveIntegerField()),
                ('next_payment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('gateway_reference', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
