# Generated by Django 5.2.7 on 2026-01-25 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_autodebit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodebit',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
