# Generated by Django 5.2.7 on 2026-01-25 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_autodebit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodebit',
            name='next_payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
