# Generated by Django 5.2.7 on 2026-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_autodebit_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
